/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas6_AbdiGunawan_182004;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author abdig
 */
public class Mhs_abdigunawan extends javax.swing.JFrame {
    Koneksi Konek = new Koneksi();
    private Connection Con;
    Statement Stm;
    ResultSet Rs;
    String Sql;
    DefaultTableModel Dtm;
        
    public Mhs_abdigunawan() {
        initComponents();
        addJurusan();
        addAgama();
        tampilMhs();
    }

    
    void addJurusan() {
        cmbJurusan.addItem("Teknik Informatika");
        cmbJurusan.addItem("Sistem Informasi");
        cmbJurusan.addItem("Manajemen Informatika");
        cmbJurusan.addItem("Rekayasa Perangkat Lunak");
        cmbJurusan.addItem("Bisnis Digital");
        cmbJurusan.addItem("Kewirausahaan");
        
    }
    
    void addAgama() {
        cmbAgama.addItem("Islam");
        cmbAgama.addItem("Kristen");
        cmbAgama.addItem("Katolik");
        cmbAgama.addItem("Hindu");
        cmbAgama.addItem("Buddha");    
    }
    
    
    void Bersih() {
        txtCari.setText("");
        txtNama.setText("");
        txtStambuk.setText("");
        txtStambuk.setEditable(true);
        txtTelp.setText("");
        txtAlamat.setText("");
        cmbJurusan.setSelectedIndex(0); 
        cmbAgama.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        txtAhli.setText("");
        btnSimpan.setEnabled(true);
    }
    
    private void AturJTable(JTable Lihat, int Lebar[]){
        try{
            Lihat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            int banyak = Lihat.getColumnCount();
            for (int i = 0; i < banyak; i++) {
                TableColumn Kolom = Lihat.getColumnModel().getColumn(i);
                Kolom.setPreferredWidth(Lebar[i]);
                Lihat.setRowHeight(20);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah"+e);
        }
    }
    private void TampilModelJTabel(){
        try {
            String[]kolom={"Stambuk","Nama","Jurusan","Agama","Nomor HP","Alamat","Jenis Kelamin","Keahlian"};
            Dtm = new DefaultTableModel(null, kolom){
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };
            jTable1.setModel(Dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "salah"+e);
        }
    }
 
    void tampilMhs(){
        try {
            Con=Konek.getKoneksiDatabase();
            Stm = Con.createStatement();
            TampilModelJTabel();
            try{
                Sql = Sql = "SELECT * FROM mhs_abdigunawan ";
                Rs = Stm.executeQuery(Sql);
                while(Rs.next()){
                    Dtm.addRow(new Object[]{
                        Rs.getString("stambuk"),
                        Rs.getString("nama"),
                        Rs.getString("jurusan"),
                        Rs.getString("agama"),
                        Rs.getString("nohp"),
                        Rs.getString("alamat"),
                        Rs.getString("jkel"),
                        Rs.getString("ahli"),
                    });
                    jTable1.setModel(Dtm);
                }
            }catch(Exception e){
                System.out.println("Ada Kesalahan " + e.toString());
            }
        }catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStambuk = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbJurusan = new javax.swing.JComboBox<>();
        cmbAgama = new javax.swing.JComboBox<>();
        txtTelp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtAhli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(84, 50, 141));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MAHASISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Stambuk ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Nama ");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Jurusan ");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Agama");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("No HP");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");

        txtStambuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStambukActionPerformed(evt);
            }
        });

        cmbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        cmbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));

        btnSimpan.setBackground(new java.awt.Color(54, 33, 89));
        btnSimpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(54, 33, 89));
        btnEdit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(54, 33, 89));
        btnHapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(54, 33, 89));
        btnRefresh.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki Laki");

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Keahlian");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(51, 51, 51)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtStambuk)
                                .addComponent(txtNama)
                                .addComponent(cmbJurusan, 0, 257, Short.MAX_VALUE)
                                .addComponent(cmbAgama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(85, 85, 85)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                .addComponent(txtAlamat)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(rbLaki)
                                    .addGap(14, 14, 14)
                                    .addComponent(rbPerempuan)
                                    .addGap(10, 10, 10))
                                .addComponent(txtAhli)))))
                .addGap(44, 44, 44))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtStambuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(rbLaki)
                        .addComponent(rbPerempuan)))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cmbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtAhli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilMhs();
        Bersih();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        //mengambil nilai jenis kelamin dari radio button
        String Jkel="";
        if (rbLaki.isSelected()) {
            Jkel = "Laki Laki";
        }else if (rbPerempuan.isSelected()) {
            Jkel = "Perempuan";
        }
        
        try {
            Con = Konek.getKoneksiDatabase();
            Stm = null;
            Sql = "insert into mhs_abdigunawan "
            + "values('"+txtStambuk.getText()+"','"+txtNama.getText()+
            "','"+cmbJurusan.getSelectedItem()+"','"+cmbAgama.getSelectedItem()+"','"+txtTelp.getText()+"','"+txtAlamat.getText()+"','"+Jkel+"','"+txtAhli.getText()+"')";
            Stm= Con.createStatement();
            int AdaPenambahanRecord= Stm.executeUpdate(Sql);
            if (AdaPenambahanRecord>0){
                JOptionPane.showMessageDialog(this,"Data Berhasil Tersimpan",
                    "Informasi",JOptionPane.INFORMATION_MESSAGE);
                tampilMhs();
            }
            else
            JOptionPane.showMessageDialog(this,"Data Gagal Tersimpan",
                "Informasi",JOptionPane.INFORMATION_MESSAGE);
            Stm.close();
        } catch (SQLException e){
            System.out.println("Koneksi Gagal " +e.toString());
        }
        Bersih();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }
        
        txtStambuk.setEditable(false);
        String stambuk,nama,jurusan,agama,nohp,alamat;
        txtStambuk.setText(jTable1.getValueAt(i, 0).toString());
        txtNama.setText(jTable1.getValueAt(i, 1).toString());
        cmbJurusan.setSelectedItem(jTable1.getValueAt(i, 2).toString());
        cmbAgama.setSelectedItem(jTable1.getValueAt(i, 3).toString());
        txtTelp.setText(jTable1.getValueAt(i, 4).toString());
        txtAlamat.setText(jTable1.getValueAt(i, 5).toString());
        String jenisKelamin = jTable1.getValueAt(i, 6).toString();
        if (jenisKelamin.equals("Laki Laki")) {
            rbLaki.setSelected(true);
        } else if (jenisKelamin.equals("Perempuan")) {
            rbPerempuan.setSelected(true);
        }
        txtAhli.setText(jTable1.getValueAt(i, 7).toString());
        
        btnSimpan.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        String Jkel="";
        if (rbLaki.isSelected()) {
            Jkel = "Laki Laki";
        }else if (rbPerempuan.isSelected()) {
            Jkel = "Perempuan";
        }
        
        try {
            Con = Konek.getKoneksiDatabase();
            Stm = null;
            Sql = "update mhs_abdigunawan set stambuk='"+txtStambuk.getText()+"', nama ='"+txtNama.getText()+"',"
            + "jurusan='"+cmbJurusan.getSelectedItem()+"', agama='"+cmbAgama.getSelectedItem()+"', nohp ='"+txtTelp.getText()+"',"
                    + "alamat='"+txtAlamat.getText()+"', jkel ='"+Jkel+"', ahli ='"+txtAhli.getText()+"' where stambuk ='"+txtStambuk.getText()+"' ";
            Stm= Con.createStatement();
            int AdaPenambahanRecord= Stm.executeUpdate(Sql);
            tampilMhs();
            if (AdaPenambahanRecord>0)
            JOptionPane.showMessageDialog(this,"Data Berhasil Terupdate",
                "Informasi",JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,"Data Gagal Terupdate",
                "Informasi",JOptionPane.INFORMATION_MESSAGE);
            Stm.close();
        } catch (SQLException e){
            System.out.println("Koneksi Gagal " +e.toString());
        }
        Bersih();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            Con = Konek.getKoneksiDatabase();
            Stm = null;
            Sql = "delete from mhs_abdigunawan where stambuk ='"+txtStambuk.getText()+"' ";
            Stm= Con.createStatement();
            int AdaPenambahanRecord= Stm.executeUpdate(Sql);
            tampilMhs();
            if (AdaPenambahanRecord>0)
            JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus",
                "Informasi",JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,"Data Gagal Dihapus",
                "Informasi",JOptionPane.INFORMATION_MESSAGE);
            Stm.close();
        } catch (SQLException e){
            System.out.println("Koneksi Gagal " +e.toString());
        }
        Bersih();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        try {
            Con=Konek.getKoneksiDatabase();
            Stm = Con.createStatement();
            TampilModelJTabel();
            Sql = "select * from mhs_abdigunawan where stambuk LIKE '%"+txtCari.getText()+"%' OR nama LIKE '%"+txtCari.getText()+"%' OR jurusan LIKE '%"+txtCari.getText()+"%' "
                    + " OR agama LIKE '%"+txtCari.getText()+"%' OR nohp LIKE '%"+txtCari.getText()+"%' OR alamat LIKE '%"+txtCari.getText()+"%'  OR jkel LIKE '%"+txtCari.getText()+"%' "
                    + " OR ahli LIKE '%"+txtCari.getText()+"%' ";
            Rs = Stm.executeQuery(Sql);
            while(Rs.next()){
                Dtm.addRow(new Object[]{
                    Rs.getString("stambuk"),
                    Rs.getString("nama"), 
                    Rs.getString("jurusan"),
                    Rs.getString("agama"),
                    Rs.getString("nohp"),
                    Rs.getString("alamat"),
                    Rs.getString("jkel"),
                    Rs.getString("ahli"),
                    
                });
            jTable1.setModel(Dtm);
            }
        }catch(Exception e){
            System.out.println("Ada Kesalahan " + e.toString());
        }        
    }//GEN-LAST:event_txtCariKeyPressed

    private void txtStambukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStambukActionPerformed
        // TODO add your handling code here:
        try {
            Con = Konek.getKoneksiDatabase();
            Sql = "Select * from mhs_abdigunawan where stambuk='" +txtStambuk.getText()+"'";
            Stm= Con.createStatement();
            Rs = Stm.executeQuery(Sql);
            if (Rs.next()){
                JOptionPane.showMessageDialog(this,
                    "Mahasiswa Tersebut Sudah Ada Silahkan Input Stambuk Lain Atau Data Mau Di Edit",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                txtNama.setText(Rs.getString("nama"));
                txtTelp.setText(Rs.getString("nohp"));
                txtAlamat.setText(Rs.getString("alamat"));
                cmbJurusan.setSelectedItem(Rs.getString("jurusan"));
                cmbAgama.setSelectedItem(Rs.getString("agama"));
                String jenisKelamin = (Rs.getString("jkel"));
                if (jenisKelamin.equals("Laki Laki")) {
                    rbLaki.setSelected(true);
                } else if (jenisKelamin.equals("Perempuan")) {
                    rbPerempuan.setSelected(true);
                }
                txtAhli.setText(Rs.getString("ahli"));
                btnSimpan.setEnabled(false);
            }else{
                txtNama.requestFocus();
                txtNama.setText("");
                txtTelp.setText("");
                txtAlamat.setText("");
                cmbJurusan.setSelectedIndex(0); 
                cmbAgama.setSelectedIndex(0);
                buttonGroup1.clearSelection();
                txtAhli.setText("");
                btnSimpan.setEnabled(true);
            }
        }catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_txtStambukActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mhs_abdigunawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mhs_abdigunawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mhs_abdigunawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mhs_abdigunawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mhs_abdigunawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAgama;
    private javax.swing.JComboBox<String> cmbJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtAhli;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStambuk;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
